# Single Model Promotion Pipeline
# 
# This pipeline promotes a single model to the registry with approval.
# Triggered by the main training pipeline for each model individually.

parameters:
  - name: modelName
    type: string
    displayName: 'Model Name'
  
  - name: modelVersion
    type: string
    displayName: 'Model Version'
  
  - name: plantId
    type: string
    displayName: 'Plant ID'
  
  - name: circuitId
    type: string
    displayName: 'Circuit ID'
  
  - name: trainingHash
    type: string
    displayName: 'Training Hash'
  
  - name: cutoffDate
    type: string
    displayName: 'Cutoff Date'

variables:
  - group: mlops-dev-variables
  - group: mlops-registry-variables
  - group: mlops-pipeline-settings
  
  # Model display name for approval UI
  - name: modelDisplayName
    value: '${{ parameters.plantId }}/${{ parameters.circuitId }} - ${{ parameters.modelName }}:v${{ parameters.modelVersion }}'

stages:
  - stage: ApprovePromotion
    displayName: 'Approve Model Promotion'
    jobs:
      - deployment: ApproveModel
        displayName: 'Approve: ${{ parameters.modelName }}'
        # Single environment for all models (change to plant-specific later)
        environment: 'registry-promotion'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - script: |
                    echo "╔════════════════════════════════════════════════════════════╗"
                    echo "║           MODEL PROMOTION APPROVAL REQUEST                ║"
                    echo "╚════════════════════════════════════════════════════════════╝"
                    echo ""
                    echo "Plant:         ${{ parameters.plantId }}"
                    echo "Circuit:       ${{ parameters.circuitId }}"
                    echo "Model:         ${{ parameters.modelName }}"
                    echo "Version:       ${{ parameters.modelVersion }}"
                    echo "Training Hash: ${{ parameters.trainingHash }}"
                    echo "Cutoff Date:   ${{ parameters.cutoffDate }}"
                    echo ""
                    echo "This model will be promoted to the shared Azure ML Registry"
                    echo "for deployment to Test and Production environments."
                    echo ""
                  displayName: 'Show Model Details'
                
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '$(pythonVersion)'
                
                - script: pip install azure-ai-ml azure-identity
                  displayName: 'Install dependencies'
                
                - task: AzureCLI@2
                  displayName: 'Promote Model to Registry'
                  inputs:
                    azureSubscription: '$(azureServiceConnection)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      echo "🚀 Promoting model to registry..."
                      
                      # Check if already exists in registry
                      if az ml model show \
                        --name "${{ parameters.modelName }}" \
                        --version "${{ parameters.modelVersion }}" \
                        --registry-name "$(registryName)" \
                        --resource-group "$(registryResourceGroup)" &>/dev/null; then
                        echo "ℹ️  Model already exists in registry, skipping"
                        exit 0
                      fi
                      
                      # Share model to registry (preserves lineage)
                      echo "Sharing ${{ parameters.modelName }}:v${{ parameters.modelVersion }} to registry..."
                      echo "Using --share to preserve lineage and maintain single source of truth"
                      
                      az ml model share \
                        --name "${{ parameters.modelName }}" \
                        --version "${{ parameters.modelVersion }}" \
                        --workspace-name "$(workspaceName)" \
                        --resource-group "$(resourceGroup)" \
                        --registry-name "$(registryName)" \
                        --share-with-name "${{ parameters.modelName }}" \
                        --share-with-version "${{ parameters.modelVersion }}"
                      
                      if [ $? -eq 0 ]; then
                        echo "✅ Model shared successfully (lineage preserved)"
                        
                        # Wait for model to appear in registry with exponential backoff
                        echo "⏳ Waiting for model to be available in registry..."
                        
                        # Get settings from Variable Groups (with defaults)
                        MAX_WAIT_SECONDS=${registryPropagationMaxWaitSeconds:-120}
                        INITIAL_DELAY=${registryPropagationInitialDelaySeconds:-2}
                        MAX_DELAY=${registryPropagationMaxDelaySeconds:-30}
                        
                        echo "Settings: max_wait=${MAX_WAIT_SECONDS}s, initial_delay=${INITIAL_DELAY}s, max_delay=${MAX_DELAY}s"
                        
                        ELAPSED=0
                        CURRENT_DELAY=$INITIAL_DELAY
                        ATTEMPT=1
                        
                        while [ $ELAPSED -lt $MAX_WAIT_SECONDS ]; do
                          if az ml model show \
                            --name "${{ parameters.modelName }}" \
                            --version "${{ parameters.modelVersion }}" \
                            --registry-name "$(registryName)" \
                            --resource-group "$(registryResourceGroup)" &>/dev/null; then
                            echo "✅ Verified in registry (after ${ELAPSED}s, attempt $ATTEMPT)"
                            echo "🔗 Lineage maintained: Registry model points to workspace model"
                            break
                          fi
                          
                          echo "   Attempt $ATTEMPT: Not found yet, waiting ${CURRENT_DELAY}s..."
                          sleep $CURRENT_DELAY
                          ELAPSED=$((ELAPSED + CURRENT_DELAY))
                          
                          # Exponential backoff: double delay up to max
                          CURRENT_DELAY=$((CURRENT_DELAY * 2))
                          if [ $CURRENT_DELAY -gt $MAX_DELAY ]; then
                            CURRENT_DELAY=$MAX_DELAY
                          fi
                          
                          ATTEMPT=$((ATTEMPT + 1))
                        done
                        
                        # Check if we exited due to timeout
                        if ! az ml model show \
                          --name "${{ parameters.modelName }}" \
                          --version "${{ parameters.modelVersion }}" \
                          --registry-name "$(registryName)" \
                          --resource-group "$(registryResourceGroup)" &>/dev/null; then
                          echo "⚠️  Model shared but not visible in registry after ${MAX_WAIT_SECONDS}s"
                          echo "⚠️  This may be a propagation delay - check registry manually"
                          exit 1
                        fi
                      else
                        echo "❌ Share failed"
                        exit 1
                      fi
